version: '3.2'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - './volume/redis/redis-data:/data'
      - './volume/redis/redis.conf:/usr/local/etc/redis/redis.conf'
  app:
    build: '.'
    ports:
      - '3001:3001'
    depends_on:
      - 'redis'
    environment:
      REDIS_HOST: redis
      PGHOST: postgres
      PGPORT: 5432
      POSTGRES_USER: bstats
      POSTGRES_PASSWORD: bstats
      POSTGRES_DB: bstats
    volumes:
      - './service-account-file.json:/app/service-account-file.json'
